### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by thomaspijper** [Zyin055/Inspect-Embedding-Training#5]
When setting the VECTOR_GRAPH_CREATE_LIMITED_GRAPH bool to True, I get the following crash:

```
Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\textual_inversion\2023-01-19\xyz\inspect_embedding_training.py", line 453, in <module>
    main()
  File "E:\StableDiffusion\stable-diffusion-webui\textual_inversion\2023-01-19\xyz\inspect_embedding_training.py", line 431, in main
    create_vector_plot(title=embed_name if GRAPH_SHOW_TITLE else None,
  File "E:\StableDiffusion\stable-diffusion-webui\textual_inversion\2023-01-19\xyz\inspect_embedding_training.py", line 314, in create_vector_plot
    magnitude = get_vector_data_magnitude(data, highest_step)
  File "E:\StableDiffusion\stable-diffusion-webui\textual_inversion\2023-01-19\xyz\inspect_embedding_training.py", line 342, in get_vector_data_magnitude
    value = math.sqrt(value) / vectors_per_token
ZeroDivisionError: float division by zero
```

The error is encountered regardless of how I set VECTOR_GRAPH_LIMITED_GRAPH_NUM_VECTORS.

The problematic function is apparently:

```
def get_vector_data_magnitude(data: dict[int, dict[int, Tensor]], step: int) -> float:
    value = 0
    for n in data[step]:
        value += pow(n, 2)
    vectors_per_token = int(len(data[step]) / DIMS_PER_VECTOR)  # ie: 1, 3, 10, etc
    value = math.sqrt(value) / vectors_per_token
    return value
```

In my case, it appears that `len(data[step]) / DIMS_PER_VECTOR` is always < 1 and thus becomes 0 when cast to int. I'm not sure what conditions need to be met for `vectors_per_token` to be 1, 3, 10, etc., but my case doesn't meet them.

I've modified the function as follows to solve the problem for me.

```
def get_vector_data_magnitude(data: dict[int, dict[int, Tensor]], step: int) -> float:
    value = 0
    for n in data[step]:
        value += pow(n, 2)
    vectors_per_token = int(len(data[step]) / DIMS_PER_VECTOR)  # ie: 1, 3, 10, etc
    if vectors_per_token < 1:
        vectors_per_token = 1
    value = math.sqrt(value) / vectors_per_token
    return value
```
With this, the generated limited graph is as expected.

**Comment by Zyin055** [comment]
Your proposed solution is a bandaid that only works for 1 vector per token embeddings. I've implemented the correct solution.

Let me know if the newest update fixed it for you.

**Comment by thomaspijper** [comment]
It was a band-aid indeed. The new version fixed the problem for me, many thanks!
